
spring:
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/softwareMall
    username: root
    password: hsk200311


  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  application:
    name: softwareMall-server
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


#spring事务管理日志
#logging:
#  level:
#    org.springframework.jdbc.support.JdbcTransactionManager: debug
#  pattern:
#    dateformat: HH:mm:ss:SSS
#  file:
#    path: "logs/${spring.application.name}"
